# FSXL_VOLUME_ID=$(aws fsx describe-file-systems --query 'FileSystems[].FileSystemId' --output text)
# DNS_NAME=$(aws fsx describe-file-systems --query 'FileSystems[].DNSName' --output text)
# MOUNT_NAME=$(aws fsx describe-file-systems --query 'FileSystems[].LustreConfiguration.MountName' --output text)
# sed -i'' -e "s/FSXL_VOLUME_ID/$FSXL_VOLUME_ID/g" sysprep-new.yaml
# sed -i'' -e "s/DNS_NAME/$DNS_NAME/g" sysprep-new.yaml
# sed -i'' -e "s/MOUNT_NAME/$MOUNT_NAME/g" sysprep-new.yaml

apiVersion: batch/v1
kind: Job
metadata:
  name: sysprep
spec:  
  template:
    metadata:
      labels:
        app: sysprep
    spec:
      nodeSelector:
        karpenter.sh/nodepool: sysprep
      restartPolicy: OnFailure
      initContainers:
      - name: cache
        image: public.ecr.aws/parikshit/lustre-client:latest
        command: ["bash"]
        securityContext:
          privileged: true
        args: ["-c","echo 'sysprep started' >> /work-dir/sysprep `date` && find /work-dir/Mistral-7B-Instruct-v0.2 -type f -print0 | xargs -0 -n 1 -P 8 lfs hsm_restore && echo 'sysprep done' >> /work-dir/sysprep `date`"]
        volumeMounts:
        - name:  persistent-storage
          mountPath: "/work-dir"
      containers:
      - name: validate
        image: public.ecr.aws/parikshit/lustre-client:latest
        command: ["bash"]
        securityContext:
          privileged: true
        args: ["-c","echo 'sysprep-validation started' >> /work-dir/sysprep `date` && find /work-dir/Mistral-7B-Instruct-v0.2 -type f -print0 | xargs -0 -n 1 -P 8 lfs hsm_action >> /work-dir/sysprep && echo 'sysprep-validation done' >> /work-dir/sysprep `date`"]
        volumeMounts:
        - name:  persistent-storage
          mountPath: "/work-dir"
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: fsx-lustre-claim-sysprep
--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fsx-lustre-claim-sysprep
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1200Gi
  volumeName: fsx-pv-sysprep
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fsx-pv-sysprep
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - flock
  csi:
    driver: fsx.csi.aws.com
    volumeHandle: FSXL_VOLUME_ID
    volumeAttributes:
      dnsname: DNS_NAME
      mountname: MOUNT_NAME

