# FSXL_VOLUME_ID=$(aws fsx describe-file-systems --query 'FileSystems[].FileSystemId' --output text)
# DNS_NAME=$(aws fsx describe-file-systems --query 'FileSystems[].DNSName' --output text)
# MOUNT_NAME=$(aws fsx describe-file-systems --query 'FileSystems[].LustreConfiguration.MountName' --output text)
# sed -i'' -e "s/FSXL_VOLUME_ID/$FSXL_VOLUME_ID/g" sysprep.yaml
# sed -i'' -e "s/DNS_NAME/$DNS_NAME/g" sysprep.yaml
# sed -i'' -e "s/MOUNT_NAME/$MOUNT_NAME/g" sysprep.yaml

apiVersion: batch/v1
kind: Job
metadata:
  name: sysprep
spec:  
  template:
    metadata:
      labels:
        app: sysprep
    spec:
      nodeSelector:
        karpenter.sh/nodepool: sysprep
      restartPolicy: OnFailure
      initContainers:
      - name: copy
        image: nicolaka/netshoot
        command: ["/bin/bash"]
        args: ["-c","echo 'sysprep started' >> /work-dir/sysprep `date` && cp -r /work-dir/Mistral-7B-Instruct-v0.2 /work-dir/Temp-Mistral-7B-Instruct-v0.2"]
        volumeMounts:
        - name:  persistent-storage
          mountPath: "/work-dir"
      containers:
      - name: delete
        image: nicolaka/netshoot
        command: ["/bin/bash"]
        args: ["-c", "echo 'sysprep done' >> /work-dir/sysprep `date` && rm -rf /work-dir/Temp-Mistral-7B-Instruct-v0.2"]
        volumeMounts:
        - name:  persistent-storage
          mountPath: "/work-dir"
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: fsx-lustre-claim-sysprep
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fsx-lustre-claim-sysprep
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1200Gi
  volumeName: fsx-pv-sysprep
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fsx-pv-sysprep
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - flock
  csi:
    driver: fsx.csi.aws.com
    volumeHandle: FSXL_VOLUME_ID
    volumeAttributes:
      dnsname: DNS_NAME
      mountname: MOUNT_NAME

